apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: sfmatt/webhook-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-certs
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: webhook-certs
