apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-badpod-webhook
webhooks:
  - name: deny.badpod.webhook.dev
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: /validate
        port: 443
      caBundle: <REPLACE_WITH_BASE64_CA>
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
